# -*- mode: ruby -*-
# vi: set ft=ruby :
# changes:
# - tomas 11/07/2016 new dev branch for lubuntu desktop (16.04) LTS - 3 years support
# - tomas 15/06/2016 chagned to xenial (ubuntu 16.04).
# - tomas 20/05/2016 changed from precise64 (ubuntu 12.04) to trusty64 (ubuntu 14.04) - newer version of packages,
# - tomas 19/07/2016 changed to lubuntu 16.04 and insert_key false to prevent second vagrant up fail
#                    added start.sh provision to run always - starts background processes
# - tomas 02/08/2016 changed back to xenial (ubuntu 16.04) - desktop is installed with bootstrapdesktop.sh
# - tomas 09/08/2016 changed proxy config based on environment variables rather than manually hardcoded
# - tomas 26/08/2016 prepared cernvm box (17MB) for initial startup

$script = <<SCRIPT
echo Provisioning CernVM...
usermod -G wheel,docker,users,vagrant vagrant
passwd -d vagrant
echo "CERNVM_USER=vagrant" >> /etc/cernvm/site.conf
echo "CERNVM_START_XDM=on" >> /etc/cernvm/site.conf
echo "CERNVM_AUTOLOGIN=on" >> /etc/cernvm/site.conf
/etc/cernvm/config -x
date > /etc/vagrant_provisioned_at
/sbin/telinit 5
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "../vmcontext/westlifecernvmsl7.box"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http     =  ENV["http_proxy"] #"http://wwwcache.dl.ac.uk:8080"
    end
    if ENV["https_proxy"]
      config.proxy.https    = ENV["https_proxy"] #"http://wwwcache.dl.ac.uk:8080"
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"] #"localhost,127.0.0.1"
    end
  end
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--vram", "16"]
  end
  config.ssh.keys_only = false
  config.ssh.password = vagrant
  config.vm.synced_folder ".", "/vagrant"
  config.vm.boot_timeout = 1200
  config.vm.network "private_network", type: "dhcp", auto_config: false
  config.vm.provision "shell", inline: $script
#  config.vm.provision "shell",  path: "bootstrap.sh"
end
