# -*- mode: ruby -*-
# vi: set ft=ruby :
# changes: 
# - tomas 20/05/2016 changed from precise64 (ubuntu 12.04) to trusty64 (ubuntu 14.04) - newer version of packages, 
#                    added start.sh provision to run always - starts background processes

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://wwwcache.dl.ac.uk:8080"
    config.proxy.https    = "https://wwwcache.dl.ac.uk:8080"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end


  config.vm.provision "shell",  path: "bootstrap.sh"
end
