<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vagrant
 * Date: Thu, 31 Mar 2016 08:28:04 +0000
 */

$conf['title'] = 'Westlife prototype';
$conf['sidebar'] = '';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '2';
$conf['compress'] = 0;
$conf['plugin']['wrap']['noPrefix'] = 'tabs, group, draggable, drag-drop, dropzone';

// end auto-generated content
